runtime: nodejs18

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(?i)(.*\.(json|ico|js|css|png|jpg))
    static_files: build/\1
    upload: build/(?i)(.*\.(json|ico|js|css|png|jpg))

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always